/*************************************************************************
 *** FORTE Library Element
 ***
 *** This file was generated using the 4DIAC FORTE Export Filter V1.0.x!
 ***
 *** Name: CRANE_1_SUBSCRIBE
 *** Description: Composite Function Block Type
 *** Version: 
 ***     1.0: 2019-04-13/adeel - null - 
 *************************************************************************/

#include "CRANE_1_SUBSCRIBE.h"
#ifdef FORTE_ENABLE_GENERATED_SOURCE_CPP
#include "CRANE_1_SUBSCRIBE_gen.cpp"
#endif

DEFINE_FIRMWARE_FB(FORTE_CRANE_1_SUBSCRIBE, g_nStringIdCRANE_1_SUBSCRIBE)

const CStringDictionary::TStringId FORTE_CRANE_1_SUBSCRIBE::scm_anDataOutputNames[] = {g_nStringIdE_STOP, g_nStringIdTEXT_BOX, g_nStringIdN_CTM, g_nStringIdN_FME, g_nStringIdN_FMA, g_nStringIdCHOOSE_CRANE, g_nStringIdACTIVATE_BRIDGE, g_nStringIdACTIVATE_TROLLEY, g_nStringIdHOOK_U_IN, g_nStringIdHOOK_D_IN, g_nStringIdX_CTM, g_nStringIdY_CTM, g_nStringIdX_FME, g_nStringIdY_FME, g_nStringIdX_FMA, g_nStringIdY_FMA};

const CStringDictionary::TStringId FORTE_CRANE_1_SUBSCRIBE::scm_anDataOutputTypeIds[] = {g_nStringIdBOOL, g_nStringIdINT, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdINT, g_nStringIdINT, g_nStringIdINT, g_nStringIdINT, g_nStringIdINT, g_nStringIdINT};

const TForteInt16 FORTE_CRANE_1_SUBSCRIBE::scm_anEIWithIndexes[] = {-1};
const CStringDictionary::TStringId FORTE_CRANE_1_SUBSCRIBE::scm_anEventInputNames[] = {g_nStringIdINIT};

const TDataIOID FORTE_CRANE_1_SUBSCRIBE::scm_anEOWith[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 255, 10, 11, 12, 13, 14, 15, 255};
const TForteInt16 FORTE_CRANE_1_SUBSCRIBE::scm_anEOWithIndexes[] = {-1, 0, 11, -1};
const CStringDictionary::TStringId FORTE_CRANE_1_SUBSCRIBE::scm_anEventOutputNames[] = {g_nStringIdINITO, g_nStringIdCONTROL_E, g_nStringIdLOC_E};

const SFBInterfaceSpec FORTE_CRANE_1_SUBSCRIBE::scm_stFBInterfaceSpec = {
  1,  scm_anEventInputNames,  0,  scm_anEIWithIndexes,
  3,  scm_anEventOutputNames,  scm_anEOWith, scm_anEOWithIndexes,  0,  0, 0, 
  16,  scm_anDataOutputNames, scm_anDataOutputTypeIds,
  0, 0
};


const SCFB_FBInstanceData FORTE_CRANE_1_SUBSCRIBE::scm_astInternalFBs[] = {
  {g_nStringIdSUBSCRIBE_1, g_nStringIdSUBSCRIBE_1},
  {g_nStringIdSUBSCRIBE_1_1, g_nStringIdSUBSCRIBE_1},
  {g_nStringIdSUBSCRIBE_1_2, g_nStringIdSUBSCRIBE_1},
  {g_nStringIdSUBSCRIBE_1_3, g_nStringIdSUBSCRIBE_1},
  {g_nStringIdSUBSCRIBE_1_4, g_nStringIdSUBSCRIBE_1},
  {g_nStringIdSUBSCRIBE_1_5, g_nStringIdSUBSCRIBE_1},
  {g_nStringIdSUBSCRIBE_1_6, g_nStringIdSUBSCRIBE_1},
  {g_nStringIdSUBSCRIBE_1_7, g_nStringIdSUBSCRIBE_1},
  {g_nStringIdSUBSCRIBE_1_8, g_nStringIdSUBSCRIBE_1},
  {g_nStringIdSUBSCRIBE_1_9, g_nStringIdSUBSCRIBE_1},
  {g_nStringIdSUBSCRIBE_1_10, g_nStringIdSUBSCRIBE_1},
  {g_nStringIdSUBSCRIBE_1_11, g_nStringIdSUBSCRIBE_1},
  {g_nStringIdSUBSCRIBE_1_12, g_nStringIdSUBSCRIBE_1},
  {g_nStringIdSUBSCRIBE_1_13, g_nStringIdSUBSCRIBE_1},
  {g_nStringIdSUBSCRIBE_1_14, g_nStringIdSUBSCRIBE_1},
  {g_nStringIdSUBSCRIBE_1_15, g_nStringIdSUBSCRIBE_1},
  {g_nStringIdN_FMA, g_nStringIdBOOL2BOOL},
  {g_nStringIdE_STOP, g_nStringIdBOOL2BOOL},
  {g_nStringIdN_CTM, g_nStringIdBOOL2BOOL},
  {g_nStringIdN_FME, g_nStringIdBOOL2BOOL},
  {g_nStringIdTEXT_BOX, g_nStringIdINT2INT},
  {g_nStringIdCHOOSE_CRANE, g_nStringIdBOOL2BOOL},
  {g_nStringIdACTIVATE_BRIDGE, g_nStringIdBOOL2BOOL},
  {g_nStringIdX_CTM, g_nStringIdINT2INT},
  {g_nStringIdACTIVATE_TROLLEY, g_nStringIdBOOL2BOOL},
  {g_nStringIdHOOK_U_IN, g_nStringIdBOOL2BOOL},
  {g_nStringIdHOOK_D_IN, g_nStringIdBOOL2BOOL},
  {g_nStringIdY_CTM, g_nStringIdINT2INT},
  {g_nStringIdX_FME, g_nStringIdINT2INT},
  {g_nStringIdY_FME, g_nStringIdINT2INT},
  {g_nStringIdX_FMA, g_nStringIdINT2INT},
  {g_nStringIdY_FMA, g_nStringIdINT2INT},
  {g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdSUBSCRIBER_E_CONTROLLER},
};

const SCFB_FBParameter FORTE_CRANE_1_SUBSCRIBE::scm_astParamters[] = {
  {0, g_nStringIdQI, "1"},
  {0, g_nStringIdID, "opc_ua[/Objects/1:CRANE1A]"},
  {1, g_nStringIdQI, "1"},
  {1, g_nStringIdID, "opc_ua[/Objects/1:CRANE1B]"},
  {2, g_nStringIdQI, "1"},
  {2, g_nStringIdID, "opc_ua[/Objects/1:CRANE1C]"},
  {3, g_nStringIdQI, "1"},
  {3, g_nStringIdID, "opc_ua[/Objects/1:CRANE1D]"},
  {4, g_nStringIdQI, "1"},
  {4, g_nStringIdID, "opc_ua[/Objects/1:CRANE1E]"},
  {5, g_nStringIdQI, "1"},
  {5, g_nStringIdID, "opc_ua[/Objects/1:CRANE1F]"},
  {6, g_nStringIdQI, "1"},
  {6, g_nStringIdID, "opc_ua[/Objects/1:CRANE1G]"},
  {7, g_nStringIdQI, "1"},
  {7, g_nStringIdID, "opc_ua[/Objects/1:CRANE1H]"},
  {8, g_nStringIdQI, "1"},
  {8, g_nStringIdID, "opc_ua[/Objects/1:CRANE1I]"},
  {9, g_nStringIdQI, "1"},
  {9, g_nStringIdID, "opc_ua[/Objects/1:CRANE1J]"},
  {10, g_nStringIdQI, "1"},
  {10, g_nStringIdID, "opc_ua[/Objects/1:CRANE1K]"},
  {11, g_nStringIdQI, "1"},
  {11, g_nStringIdID, "opc_ua[/Objects/1:CRANE1L]"},
  {12, g_nStringIdQI, "1"},
  {12, g_nStringIdID, "opc_ua[/Objects/1:CRANE1M]"},
  {13, g_nStringIdQI, "1"},
  {13, g_nStringIdID, "opc_ua[/Objects/1:CRANE1N]"},
  {14, g_nStringIdQI, "1"},
  {14, g_nStringIdID, "opc_ua[/Objects/1:CRANE1O]"},
  {15, g_nStringIdQI, "1"},
  {15, g_nStringIdID, "opc_ua[/Objects/1:CRANE1P]"},
};

const SCFB_FBConnectionData FORTE_CRANE_1_SUBSCRIBE::scm_astEventConnections[] = {
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_1, g_nStringIdINITO), 1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_2, g_nStringIdINIT), 2},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_2, g_nStringIdINITO), 2, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_3, g_nStringIdINIT), 3},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_4, g_nStringIdINITO), 4, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_5, g_nStringIdINIT), 5},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_5, g_nStringIdINITO), 5, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_6, g_nStringIdINIT), 6},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_6, g_nStringIdINITO), 6, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_7, g_nStringIdINIT), 7},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_7, g_nStringIdINITO), 7, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_8, g_nStringIdINIT), 8},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_8, g_nStringIdINITO), 8, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_9, g_nStringIdINIT), 9},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_9, g_nStringIdINITO), 9, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_10, g_nStringIdINIT), 10},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_10, g_nStringIdINITO), 10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_11, g_nStringIdINIT), 11},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_11, g_nStringIdINITO), 11, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_12, g_nStringIdINIT), 12},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_12, g_nStringIdINITO), 12, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_13, g_nStringIdINIT), 13},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_13, g_nStringIdINITO), 13, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_14, g_nStringIdINIT), 14},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_14, g_nStringIdINITO), 14, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_15, g_nStringIdINIT), 15},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdINIT), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1, g_nStringIdINIT), 0},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_3, g_nStringIdINITO), 3, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_4, g_nStringIdINIT), 4},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1, g_nStringIdIND), 0, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_STOP, g_nStringIdREQ), 17},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_1, g_nStringIdIND), 1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdTEXT_BOX, g_nStringIdREQ), 20},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_2, g_nStringIdIND), 2, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdN_CTM, g_nStringIdREQ), 18},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_3, g_nStringIdIND), 3, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdN_FME, g_nStringIdREQ), 19},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_4, g_nStringIdIND), 4, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdN_FMA, g_nStringIdREQ), 16},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_5, g_nStringIdIND), 5, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCHOOSE_CRANE, g_nStringIdREQ), 21},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_6, g_nStringIdIND), 6, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdACTIVATE_BRIDGE, g_nStringIdREQ), 22},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_7, g_nStringIdIND), 7, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdACTIVATE_TROLLEY, g_nStringIdREQ), 24},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_8, g_nStringIdIND), 8, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHOOK_U_IN, g_nStringIdREQ), 25},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_9, g_nStringIdIND), 9, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHOOK_D_IN, g_nStringIdREQ), 26},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_10, g_nStringIdIND), 10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdX_CTM, g_nStringIdREQ), 23},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_11, g_nStringIdIND), 11, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdY_CTM, g_nStringIdREQ), 27},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_12, g_nStringIdIND), 12, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdX_FME, g_nStringIdREQ), 28},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_13, g_nStringIdIND), 13, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdY_FME, g_nStringIdREQ), 29},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_14, g_nStringIdIND), 14, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdX_FMA, g_nStringIdREQ), 30},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_15, g_nStringIdIND), 15, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdY_FMA, g_nStringIdREQ), 31},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_15, g_nStringIdINITO), 15, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdINITO), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1, g_nStringIdINITO), 0, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_1, g_nStringIdINIT), 1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_STOP, g_nStringIdCNF), 17, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdE_STOP_E), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdTEXT_BOX, g_nStringIdCNF), 20, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdTEXT_BOX_E), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdN_CTM, g_nStringIdCNF), 18, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdN_CTM_E), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdN_FME, g_nStringIdCNF), 19, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdN_FME_E), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdN_FMA, g_nStringIdCNF), 16, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdN_FMA_E), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCHOOSE_CRANE, g_nStringIdCNF), 21, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdCHOOSE_CRANE_E), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdACTIVATE_BRIDGE, g_nStringIdCNF), 22, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdACTIVATE_BRIDGE_E), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdACTIVATE_TROLLEY, g_nStringIdCNF), 24, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdACTIVATE_TROLLEY_E), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHOOK_U_IN, g_nStringIdCNF), 25, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdHOOK_U_E), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHOOK_D_IN, g_nStringIdCNF), 26, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdHOOK_D_E), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdX_CTM, g_nStringIdCNF), 23, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdX_CTM_E), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdY_CTM, g_nStringIdCNF), 27, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdY_CTM_E), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdX_FME, g_nStringIdCNF), 28, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdX_FME_E), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdY_FME, g_nStringIdCNF), 29, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdY_FME_E), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdX_FMA, g_nStringIdCNF), 30, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdX_FMA_E), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdY_FMA, g_nStringIdCNF), 31, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdY_FMA_E), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdCONTROL_E), 32, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdCONTROL_E), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdLOC_E), 32, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdLOC_E), -1},
};

const SCFB_FBConnectionData FORTE_CRANE_1_SUBSCRIBE::scm_astDataConnections[] = {
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1, g_nStringIdRD_1), 0, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_STOP, g_nStringIdIN), 17},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_1, g_nStringIdRD_1), 1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdTEXT_BOX, g_nStringIdIN), 20},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_2, g_nStringIdRD_1), 2, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdN_CTM, g_nStringIdIN), 18},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_3, g_nStringIdRD_1), 3, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdN_FME, g_nStringIdIN), 19},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_4, g_nStringIdRD_1), 4, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdN_FMA, g_nStringIdIN), 16},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_5, g_nStringIdRD_1), 5, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCHOOSE_CRANE, g_nStringIdIN), 21},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_6, g_nStringIdRD_1), 6, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdACTIVATE_BRIDGE, g_nStringIdIN), 22},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_7, g_nStringIdRD_1), 7, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdACTIVATE_TROLLEY, g_nStringIdIN), 24},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_8, g_nStringIdRD_1), 8, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHOOK_U_IN, g_nStringIdIN), 25},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_9, g_nStringIdRD_1), 9, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHOOK_D_IN, g_nStringIdIN), 26},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_10, g_nStringIdRD_1), 10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdX_CTM, g_nStringIdIN), 23},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_11, g_nStringIdRD_1), 11, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdY_CTM, g_nStringIdIN), 27},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_12, g_nStringIdRD_1), 12, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdX_FME, g_nStringIdIN), 28},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_13, g_nStringIdRD_1), 13, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdY_FME, g_nStringIdIN), 29},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_14, g_nStringIdRD_1), 14, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdX_FMA, g_nStringIdIN), 30},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBE_1_15, g_nStringIdRD_1), 15, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdY_FMA, g_nStringIdIN), 31},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_STOP, g_nStringIdOUT), 17, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdE_STOP_I), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdTEXT_BOX, g_nStringIdOUT), 20, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdTEXT_BOX_I), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdN_CTM, g_nStringIdOUT), 18, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdN_CTM_I), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdN_FME, g_nStringIdOUT), 19, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdN_FME_I), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdN_FMA, g_nStringIdOUT), 16, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdN_FMA_I), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCHOOSE_CRANE, g_nStringIdOUT), 21, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdCHOOSE_CRANE_I), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdACTIVATE_BRIDGE, g_nStringIdOUT), 22, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdACTIVATE_BRIDGE_I), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdACTIVATE_TROLLEY, g_nStringIdOUT), 24, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdACTIVATE_TROLLEY_I), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHOOK_U_IN, g_nStringIdOUT), 25, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdHOOK_U_I), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHOOK_D_IN, g_nStringIdOUT), 26, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdHOOK_D_I), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdX_CTM, g_nStringIdOUT), 23, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdX_CTM_I), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdY_CTM, g_nStringIdOUT), 27, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdY_CTM_I), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdX_FME, g_nStringIdOUT), 28, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdX_FME_I), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdY_FME, g_nStringIdOUT), 29, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdY_FME_I), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdX_FMA, g_nStringIdOUT), 30, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdX_FMA_I), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdY_FMA, g_nStringIdOUT), 31, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdY_FMA_I), 32},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdE_STOP_O), 32, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdE_STOP), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdTEXT_BOX_O), 32, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdTEXT_BOX), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdN_CTM_O), 32, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdN_CTM), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdN_FME_O), 32, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdN_FME), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdN_FMA_O), 32, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdN_FMA), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdCHOOSE_CRANE_O), 32, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdCHOOSE_CRANE), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdACTIVATE_BRIDGE_O), 32, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdACTIVATE_BRIDGE), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdACTIVATE_TROLLEY_O), 32, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdACTIVATE_TROLLEY), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdHOOK_U_O), 32, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdHOOK_U_IN), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdHOOK_D_O), 32, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdHOOK_D_IN), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdX_CTM_O), 32, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdX_CTM), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdY_CTM_O), 32, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdY_CTM), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdX_FME_O), 32, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdX_FME), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdY_FME_O), 32, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdY_FME), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdX_FMA_O), 32, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdX_FMA), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSUBSCRIBER_E_CONTROLLER, g_nStringIdY_FMA_O), 32, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdY_FMA), -1},
};

const SCFB_FBNData FORTE_CRANE_1_SUBSCRIBE::scm_stFBNData = {
  33, scm_astInternalFBs,
  51, scm_astEventConnections,
  0, 0,
  48, scm_astDataConnections,
  0, 0,
  32, scm_astParamters
};


