/*************************************************************************
 *** FORTE Library Element
 ***
 *** This file was generated using the 4DIAC FORTE Export Filter V1.0.x!
 ***
 *** Name: EC_SENSORS_ACTUATORS
 *** Description: Composite Function Block Type
 *** Version: 
 ***     1.0: 2019-03-30/adeel - null - 
 *************************************************************************/

#include "EC_SENSORS_ACTUATORS.h"
#ifdef FORTE_ENABLE_GENERATED_SOURCE_CPP
#include "EC_SENSORS_ACTUATORS_gen.cpp"
#endif

DEFINE_FIRMWARE_FB(FORTE_EC_SENSORS_ACTUATORS, g_nStringIdEC_SENSORS_ACTUATORS)

const CStringDictionary::TStringId FORTE_EC_SENSORS_ACTUATORS::scm_anDataInputNames[] = {g_nStringIdE_STOP, g_nStringIdCTM_ACTIVATE_SENSORS, g_nStringIdCTM_ACTIVATE_BRIDGE_I, g_nStringIdCTM_BRIGDE_F_B_I, g_nStringIdCTM_AVTIVATE_TROLLEY_I, g_nStringIdCTM_TROLLEY_F_B_I, g_nStringIdCTM_AVTIVATE_HOOK_I, g_nStringIdCTM_HOOK_U_D_I, g_nStringIdFME_ACTIVATE_SENSORS, g_nStringIdFME_ACTIVATE_BRIDGE_I, g_nStringIdFME_BRIGDE_F_B_I, g_nStringIdFME_AVTIVATE_TROLLEY_I, g_nStringIdFME_TROLLEY_F_B_I, g_nStringIdFME_AVTIVATE_HOOK_I, g_nStringIdFME_HOOK_U_D_I, g_nStringIdFMA_ACTIVATE_SENSORS, g_nStringIdFMA_ACTIVATE_BRIDGE_I, g_nStringIdFMA_BRIGDE_F_B_I, g_nStringIdFMA_AVTIVATE_TROLLEY_I, g_nStringIdFMA_TROLLEY_F_B_I, g_nStringIdFMA_AVTIVATE_HOOK_I, g_nStringIdFMA_HOOK_U_D_I};

const CStringDictionary::TStringId FORTE_EC_SENSORS_ACTUATORS::scm_anDataInputTypeIds[] = {g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL};

const TForteInt16 FORTE_EC_SENSORS_ACTUATORS::scm_anEIWithIndexes[] = {-1, 0};
const TDataIOID FORTE_EC_SENSORS_ACTUATORS::scm_anEIWith[] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 0, 255};
const CStringDictionary::TStringId FORTE_EC_SENSORS_ACTUATORS::scm_anEventInputNames[] = {g_nStringIdINIT, g_nStringIdREQ};

const TForteInt16 FORTE_EC_SENSORS_ACTUATORS::scm_anEOWithIndexes[] = {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1};
const CStringDictionary::TStringId FORTE_EC_SENSORS_ACTUATORS::scm_anEventOutputNames[] = {g_nStringIdINITO, g_nStringIdCNF, g_nStringIdACTIVATE_SENSORS_E, g_nStringIdBRIGDE_F_B_I_T, g_nStringIdBRIGDE_F_B_I_B, g_nStringIdTROLLEY_F_B_I_F, g_nStringIdTROLLEY_F_B_I_B, g_nStringIdHOOK_U_D_I_D, g_nStringIdHOOK_U_D_I_U, g_nStringIdACTIVATE_BRIDGE, g_nStringIdAVTIVATE_TROLLEY, g_nStringIdAVTIVATE_HOOK, g_nStringIdDEACTIVATE_BRIDGE, g_nStringIdDEAVTIVATE_TROLLEY, g_nStringIdDEAVTIVATE_HOOK};

const SFBInterfaceSpec FORTE_EC_SENSORS_ACTUATORS::scm_stFBInterfaceSpec = {
  2,  scm_anEventInputNames,  scm_anEIWith,  scm_anEIWithIndexes,
  15,  scm_anEventOutputNames,  0, 0,  22,  scm_anDataInputNames, scm_anDataInputTypeIds,
  0,  0, 0,
  0, 0
};


const SCFB_FBInstanceData FORTE_EC_SENSORS_ACTUATORS::scm_astInternalFBs[] = {
  {g_nStringIdCTM_11, g_nStringIdE_R_TRIG},
  {g_nStringIdCTM_12, g_nStringIdE_F_TRIG},
  {g_nStringIdCTM_21, g_nStringIdE_R_TRIG},
  {g_nStringIdCTM_22, g_nStringIdE_F_TRIG},
  {g_nStringIdCTM_31, g_nStringIdE_R_TRIG},
  {g_nStringIdCTM_32, g_nStringIdE_F_TRIG},
  {g_nStringIdCTM_41, g_nStringIdE_R_TRIG},
  {g_nStringIdCTM_42, g_nStringIdE_F_TRIG},
  {g_nStringIdFME41, g_nStringIdE_R_TRIG},
  {g_nStringIdFME_11, g_nStringIdE_R_TRIG},
  {g_nStringIdFME_32, g_nStringIdE_F_TRIG},
  {g_nStringIdFME_42, g_nStringIdE_F_TRIG},
  {g_nStringIdFME_31, g_nStringIdE_R_TRIG},
  {g_nStringIdFME_12, g_nStringIdE_F_TRIG},
  {g_nStringIdFME_21, g_nStringIdE_R_TRIG},
  {g_nStringIdFME_22, g_nStringIdE_F_TRIG},
  {g_nStringIdFMA_41, g_nStringIdE_R_TRIG},
  {g_nStringIdFMA_11, g_nStringIdE_R_TRIG},
  {g_nStringIdFMA_32, g_nStringIdE_F_TRIG},
  {g_nStringIdFMA_42, g_nStringIdE_F_TRIG},
  {g_nStringIdFMA_31, g_nStringIdE_R_TRIG},
  {g_nStringIdFMA_12, g_nStringIdE_F_TRIG},
  {g_nStringIdFMA_21, g_nStringIdE_R_TRIG},
  {g_nStringIdFMA_22, g_nStringIdE_F_TRIG},
  {g_nStringIdE_CYCLE, g_nStringIdE_CYCLE},
  {g_nStringIdE_CYCLE_1, g_nStringIdE_CYCLE},
  {g_nStringIdE_CYCLE_2, g_nStringIdE_CYCLE},
  {g_nStringIdHA_CTM, g_nStringIdE_R_TRIG},
  {g_nStringIdBA_CTM, g_nStringIdE_R_TRIG},
  {g_nStringIdTA_FME, g_nStringIdE_R_TRIG},
  {g_nStringIdBA_FMA, g_nStringIdE_R_TRIG},
  {g_nStringIdTA_CTM, g_nStringIdE_R_TRIG},
  {g_nStringIdBA_FME, g_nStringIdE_R_TRIG},
  {g_nStringIdHA_FME, g_nStringIdE_R_TRIG},
  {g_nStringIdTA_FMA, g_nStringIdE_R_TRIG},
  {g_nStringIdHA_FMA, g_nStringIdE_R_TRIG},
  {g_nStringIdBD_CTM, g_nStringIdE_F_TRIG},
  {g_nStringIdTD_CTM, g_nStringIdE_F_TRIG},
  {g_nStringIdHD_CTM, g_nStringIdE_F_TRIG},
  {g_nStringIdBD_FME, g_nStringIdE_F_TRIG},
  {g_nStringIdTD_FME, g_nStringIdE_F_TRIG},
  {g_nStringIdHD_FME, g_nStringIdE_F_TRIG},
  {g_nStringIdBD_FMA, g_nStringIdE_F_TRIG},
  {g_nStringIdTD_FMA, g_nStringIdE_F_TRIG},
  {g_nStringIdHD_FMA, g_nStringIdE_F_TRIG},
  {g_nStringIdE_STOP, g_nStringIdE_F_TRIG},
  {g_nStringIdE_F_TRIG, g_nStringIdE_F_TRIG},
};

const SCFB_FBParameter FORTE_EC_SENSORS_ACTUATORS::scm_astParamters[] = {
  {24, g_nStringIdDT, "T#100ms"},
  {25, g_nStringIdDT, "T#100ms"},
  {26, g_nStringIdDT, "T#100ms"},
};

const SCFB_FBConnectionData FORTE_EC_SENSORS_ACTUATORS::scm_astEventConnections[] = {
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_CYCLE, g_nStringIdEO), 24, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdACTIVATE_SENSORS_E), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_CYCLE_1, g_nStringIdEO), 25, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdACTIVATE_SENSORS_E), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_CYCLE_2, g_nStringIdEO), 26, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdACTIVATE_SENSORS_E), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_11, g_nStringIdEO), 0, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_CYCLE, g_nStringIdSTART), 24},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_12, g_nStringIdEO), 1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_CYCLE, g_nStringIdSTOP), 24},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdINIT), -1, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdINITO), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME_11, g_nStringIdEO), 9, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_CYCLE_1, g_nStringIdSTART), 25},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME_12, g_nStringIdEO), 13, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_CYCLE_1, g_nStringIdSTOP), 25},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_11, g_nStringIdEO), 17, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_CYCLE_2, g_nStringIdSTART), 26},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_12, g_nStringIdEO), 21, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_CYCLE_2, g_nStringIdSTOP), 26},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdREQ), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_11, g_nStringIdEI), 0},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_21, g_nStringIdEO), 2, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdBRIGDE_F_B_I_T), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_22, g_nStringIdEO), 3, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdBRIGDE_F_B_I_B), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_31, g_nStringIdEO), 4, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdTROLLEY_F_B_I_F), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_32, g_nStringIdEO), 5, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdTROLLEY_F_B_I_B), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_41, g_nStringIdEO), 6, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdHOOK_U_D_I_D), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_42, g_nStringIdEO), 7, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdHOOK_U_D_I_U), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME_21, g_nStringIdEO), 14, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdBRIGDE_F_B_I_T), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME_22, g_nStringIdEO), 15, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdBRIGDE_F_B_I_B), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME_31, g_nStringIdEO), 12, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdTROLLEY_F_B_I_F), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME_32, g_nStringIdEO), 10, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdTROLLEY_F_B_I_B), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME41, g_nStringIdEO), 8, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdHOOK_U_D_I_D), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME_42, g_nStringIdEO), 11, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdHOOK_U_D_I_U), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_21, g_nStringIdEO), 22, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdBRIGDE_F_B_I_T), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_22, g_nStringIdEO), 23, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdBRIGDE_F_B_I_B), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_31, g_nStringIdEO), 20, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdTROLLEY_F_B_I_F), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_32, g_nStringIdEO), 18, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdTROLLEY_F_B_I_B), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_41, g_nStringIdEO), 16, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdHOOK_U_D_I_D), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_42, g_nStringIdEO), 19, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdHOOK_U_D_I_U), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdBA_CTM, g_nStringIdEO), 28, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdACTIVATE_BRIDGE), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdBA_FME, g_nStringIdEO), 32, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdACTIVATE_BRIDGE), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdBA_FMA, g_nStringIdEO), 30, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdACTIVATE_BRIDGE), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdTA_CTM, g_nStringIdEO), 31, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdAVTIVATE_TROLLEY), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdTA_FME, g_nStringIdEO), 29, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdAVTIVATE_TROLLEY), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdTA_FMA, g_nStringIdEO), 34, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdAVTIVATE_TROLLEY), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHA_CTM, g_nStringIdEO), 27, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdAVTIVATE_HOOK), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHA_FME, g_nStringIdEO), 33, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdAVTIVATE_HOOK), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHA_FMA, g_nStringIdEO), 35, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdAVTIVATE_HOOK), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdBD_CTM, g_nStringIdEO), 36, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdDEACTIVATE_BRIDGE), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdBD_FME, g_nStringIdEO), 39, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdDEACTIVATE_BRIDGE), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdBD_FMA, g_nStringIdEO), 42, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdDEACTIVATE_BRIDGE), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdTD_CTM, g_nStringIdEO), 37, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdDEAVTIVATE_TROLLEY), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdTD_FME, g_nStringIdEO), 40, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdDEAVTIVATE_TROLLEY), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdTD_FMA, g_nStringIdEO), 43, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdDEAVTIVATE_TROLLEY), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHD_CTM, g_nStringIdEO), 38, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdDEAVTIVATE_HOOK), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHD_FME, g_nStringIdEO), 41, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdDEAVTIVATE_HOOK), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHD_FMA, g_nStringIdEO), 44, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdDEAVTIVATE_HOOK), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_STOP, g_nStringIdEO), 45, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdDEACTIVATE_BRIDGE), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_F_TRIG, g_nStringIdEO), 46, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_CYCLE, g_nStringIdSTOP), 24},
};

const SCFB_FBFannedOutConnectionData FORTE_EC_SENSORS_ACTUATORS::scm_astFannedOutEventConnections[] = {
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_12, g_nStringIdEI), 1},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME_11, g_nStringIdEI), 9},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME_12, g_nStringIdEI), 13},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_11, g_nStringIdEI), 17},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_12, g_nStringIdEI), 21},
  {10, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdCNF), -1},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_21, g_nStringIdEI), 2},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_22, g_nStringIdEI), 3},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_31, g_nStringIdEI), 4},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_32, g_nStringIdEI), 5},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_41, g_nStringIdEI), 6},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_42, g_nStringIdEI), 7},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME_21, g_nStringIdEI), 14},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME_22, g_nStringIdEI), 15},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME_31, g_nStringIdEI), 12},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME_32, g_nStringIdEI), 10},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME41, g_nStringIdEI), 8},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME_42, g_nStringIdEI), 11},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_21, g_nStringIdEI), 22},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_22, g_nStringIdEI), 23},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_31, g_nStringIdEI), 20},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_32, g_nStringIdEI), 18},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_41, g_nStringIdEI), 16},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_42, g_nStringIdEI), 19},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdBA_CTM, g_nStringIdEI), 28},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdTA_CTM, g_nStringIdEI), 31},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHA_CTM, g_nStringIdEI), 27},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdBA_FME, g_nStringIdEI), 32},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdTA_FME, g_nStringIdEI), 29},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHA_FME, g_nStringIdEI), 33},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdBA_FMA, g_nStringIdEI), 30},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdTA_FMA, g_nStringIdEI), 34},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHA_FMA, g_nStringIdEI), 35},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdBD_CTM, g_nStringIdEI), 36},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdTD_CTM, g_nStringIdEI), 37},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHD_CTM, g_nStringIdEI), 38},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdBD_FME, g_nStringIdEI), 39},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdTD_FME, g_nStringIdEI), 40},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHD_FME, g_nStringIdEI), 41},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdBD_FMA, g_nStringIdEI), 42},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdTD_FMA, g_nStringIdEI), 43},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHD_FMA, g_nStringIdEI), 44},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_STOP, g_nStringIdEI), 45},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_F_TRIG, g_nStringIdEI), 46},
  {47, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdDEAVTIVATE_TROLLEY), -1},
  {47, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdDEAVTIVATE_HOOK), -1},
  {48, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_CYCLE_1, g_nStringIdSTOP), 25},
  {48, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_CYCLE_2, g_nStringIdSTOP), 26},
};

const SCFB_FBConnectionData FORTE_EC_SENSORS_ACTUATORS::scm_astDataConnections[] = {
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdCTM_ACTIVATE_SENSORS), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_11, g_nStringIdQI), 0},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdFME_ACTIVATE_SENSORS), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME_11, g_nStringIdQI), 9},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdFMA_ACTIVATE_SENSORS), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_11, g_nStringIdQI), 17},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdCTM_BRIGDE_F_B_I), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_21, g_nStringIdQI), 2},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdCTM_TROLLEY_F_B_I), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_31, g_nStringIdQI), 4},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdCTM_HOOK_U_D_I), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_41, g_nStringIdQI), 6},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdFME_BRIGDE_F_B_I), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME_21, g_nStringIdQI), 14},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdFME_TROLLEY_F_B_I), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME_31, g_nStringIdQI), 12},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdFME_HOOK_U_D_I), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME41, g_nStringIdQI), 8},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdFMA_BRIGDE_F_B_I), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_21, g_nStringIdQI), 22},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdFMA_TROLLEY_F_B_I), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_31, g_nStringIdQI), 20},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdFMA_HOOK_U_D_I), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_41, g_nStringIdQI), 16},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdCTM_ACTIVATE_BRIDGE_I), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdBA_CTM, g_nStringIdQI), 28},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdCTM_AVTIVATE_TROLLEY_I), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdTA_CTM, g_nStringIdQI), 31},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdCTM_AVTIVATE_HOOK_I), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHA_CTM, g_nStringIdQI), 27},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdFME_ACTIVATE_BRIDGE_I), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdBA_FME, g_nStringIdQI), 32},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdFME_AVTIVATE_TROLLEY_I), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdTA_FME, g_nStringIdQI), 29},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdFME_AVTIVATE_HOOK_I), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHA_FME, g_nStringIdQI), 33},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdFMA_ACTIVATE_BRIDGE_I), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdBA_FMA, g_nStringIdQI), 30},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdFMA_AVTIVATE_TROLLEY_I), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdTA_FMA, g_nStringIdQI), 34},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdFMA_AVTIVATE_HOOK_I), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHA_FMA, g_nStringIdQI), 35},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdE_STOP), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_STOP, g_nStringIdQI), 45},
};

const SCFB_FBFannedOutConnectionData FORTE_EC_SENSORS_ACTUATORS::scm_astFannedOutDataConnections[] = {
  {0, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_12, g_nStringIdQI), 1},
  {1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME_12, g_nStringIdQI), 13},
  {2, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_12, g_nStringIdQI), 21},
  {3, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_22, g_nStringIdQI), 3},
  {4, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_32, g_nStringIdQI), 5},
  {5, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCTM_42, g_nStringIdQI), 7},
  {6, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME_22, g_nStringIdQI), 15},
  {7, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME_32, g_nStringIdQI), 10},
  {8, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFME_42, g_nStringIdQI), 11},
  {9, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_22, g_nStringIdQI), 23},
  {10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_32, g_nStringIdQI), 18},
  {11, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFMA_42, g_nStringIdQI), 19},
  {12, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdBD_CTM, g_nStringIdQI), 36},
  {13, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdTD_CTM, g_nStringIdQI), 37},
  {14, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHD_CTM, g_nStringIdQI), 38},
  {15, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdBD_FME, g_nStringIdQI), 39},
  {16, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdTD_FME, g_nStringIdQI), 40},
  {17, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHD_FME, g_nStringIdQI), 41},
  {18, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdBD_FMA, g_nStringIdQI), 42},
  {19, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdTD_FMA, g_nStringIdQI), 43},
  {20, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdHD_FMA, g_nStringIdQI), 44},
  {21, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_F_TRIG, g_nStringIdQI), 46},
};

const SCFB_FBNData FORTE_EC_SENSORS_ACTUATORS::scm_stFBNData = {
  47, scm_astInternalFBs,
  49, scm_astEventConnections,
  48, scm_astFannedOutEventConnections,
  22, scm_astDataConnections,
  22, scm_astFannedOutDataConnections,
  3, scm_astParamters
};


